/**
 * Workspace Routes v6.0 — Persistent saved workspaces
 * 
 * Full CRUD for user workspaces with MongoDB persistence,
 * template browsing, and fork support.
 */

const express = require('express');
const router = express.Router();
const { authMiddleware } = require('../middleware/auth');
const { asyncHandler } = require('../middleware/errorHandler');
const { getConnectionStatus } = require('../config/db');

// Try MongoDB models, fall back to in-memory
let Workspace, User;
try { Workspace = require('../models/Workspace'); } catch (e) {}
try { User = require('../models/User'); } catch (e) {}

// In-memory fallback stores
const memWorkspaces = new Map(); // userId -> [workspace]
const MAX_WORKSPACES = 50;
const MAX_SIZE = 500000;

// ─── Templates Library ──────────────────────────────────────────────
const TEMPLATES = [
  // Algorithms
  { id: 'algo-sort', name: 'Sorting Algorithms', description: 'Bubble, merge, quick sort implementations', language: 'python', category: 'algorithms', tags: ['sort', 'algorithms'],
    code: `# Sorting Algorithms Collection\nimport random\n\ndef bubble_sort(arr):\n    n = len(arr)\n    for i in range(n):\n        for j in range(0, n-i-1):\n            if arr[j] > arr[j+1]:\n                arr[j], arr[j+1] = arr[j+1], arr[j]\n    return arr\n\ndef merge_sort(arr):\n    if len(arr) <= 1: return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i]); i += 1\n        else:\n            result.append(right[j]); j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result\n\ndef quick_sort(arr):\n    if len(arr) <= 1: return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    middle = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quick_sort(left) + middle + quick_sort(right)\n\n# Test\ndata = [random.randint(1, 100) for _ in range(15)]\nprint(f"Original:    {data}")\nprint(f"Bubble sort: {bubble_sort(data.copy())}")\nprint(f"Merge sort:  {merge_sort(data.copy())}")\nprint(f"Quick sort:  {quick_sort(data.copy())}")\n` },
  { id: 'algo-search', name: 'Search Algorithms', description: 'Binary search, linear search, graph BFS/DFS', language: 'python', category: 'algorithms', tags: ['search', 'algorithms'],
    code: `# Search Algorithms\nfrom collections import deque\n\ndef binary_search(arr, target):\n    lo, hi = 0, len(arr) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if arr[mid] == target: return mid\n        elif arr[mid] < target: lo = mid + 1\n        else: hi = mid - 1\n    return -1\n\ndef bfs(graph, start):\n    visited = set([start])\n    queue = deque([start])\n    order = []\n    while queue:\n        node = queue.popleft()\n        order.append(node)\n        for neighbor in graph.get(node, []):\n            if neighbor not in visited:\n                visited.add(neighbor)\n                queue.append(neighbor)\n    return order\n\ndef dfs(graph, start, visited=None):\n    if visited is None: visited = set()\n    visited.add(start)\n    result = [start]\n    for neighbor in graph.get(start, []):\n        if neighbor not in visited:\n            result.extend(dfs(graph, neighbor, visited))\n    return result\n\n# Test binary search\narr = list(range(1, 21))\nprint(f"Array: {arr}")\nprint(f"Search for 15: index {binary_search(arr, 15)}")\nprint(f"Search for 99: index {binary_search(arr, 99)}")\n\n# Test graph search\ngraph = {'A': ['B', 'C'], 'B': ['D', 'E'], 'C': ['F'], 'D': [], 'E': ['F'], 'F': []}\nprint(f"\\nBFS from A: {bfs(graph, 'A')}")\nprint(f"DFS from A: {dfs(graph, 'A')}")\n` },
  { id: 'algo-dp', name: 'Dynamic Programming', description: 'Fibonacci, knapsack, LCS problems', language: 'python', category: 'algorithms', tags: ['dp', 'algorithms'],
    code: `# Dynamic Programming Patterns\n\ndef fibonacci(n, memo={}):\n    if n in memo: return memo[n]\n    if n <= 1: return n\n    memo[n] = fibonacci(n-1, memo) + fibonacci(n-2, memo)\n    return memo[n]\n\ndef knapsack(weights, values, capacity):\n    n = len(weights)\n    dp = [[0] * (capacity + 1) for _ in range(n + 1)]\n    for i in range(1, n + 1):\n        for w in range(capacity + 1):\n            dp[i][w] = dp[i-1][w]\n            if weights[i-1] <= w:\n                dp[i][w] = max(dp[i][w], dp[i-1][w - weights[i-1]] + values[i-1])\n    return dp[n][capacity]\n\ndef longest_common_subsequence(s1, s2):\n    m, n = len(s1), len(s2)\n    dp = [[0] * (n + 1) for _ in range(m + 1)]\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            if s1[i-1] == s2[j-1]: dp[i][j] = dp[i-1][j-1] + 1\n            else: dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n    return dp[m][n]\n\nprint(f"Fibonacci(30): {fibonacci(30)}")\nprint(f"Knapsack: {knapsack([2,3,4,5], [3,4,5,6], 8)}")\nprint(f"LCS('ABCBDAB', 'BDCAB'): {longest_common_subsequence('ABCBDAB', 'BDCAB')}")\n` },

  // Data Structures
  { id: 'ds-linked-list', name: 'Linked List', description: 'Singly linked list with all operations', language: 'javascript', category: 'data-structures', tags: ['linked-list', 'data-structures'],
    code: `// Linked List Implementation\nclass Node {\n  constructor(val) { this.val = val; this.next = null; }\n}\n\nclass LinkedList {\n  constructor() { this.head = null; this.size = 0; }\n  \n  push(val) {\n    const node = new Node(val);\n    if (!this.head) { this.head = node; }\n    else { let cur = this.head; while (cur.next) cur = cur.next; cur.next = node; }\n    this.size++;\n    return this;\n  }\n  \n  pop() {\n    if (!this.head) return null;\n    if (!this.head.next) { const val = this.head.val; this.head = null; this.size--; return val; }\n    let cur = this.head;\n    while (cur.next.next) cur = cur.next;\n    const val = cur.next.val; cur.next = null; this.size--;\n    return val;\n  }\n  \n  reverse() {\n    let prev = null, cur = this.head;\n    while (cur) { const next = cur.next; cur.next = prev; prev = cur; cur = next; }\n    this.head = prev;\n    return this;\n  }\n  \n  toArray() {\n    const arr = []; let cur = this.head;\n    while (cur) { arr.push(cur.val); cur = cur.next; }\n    return arr;\n  }\n  \n  toString() { return this.toArray().join(' -> '); }\n}\n\nconst list = new LinkedList();\n[1, 2, 3, 4, 5].forEach(v => list.push(v));\nconsole.log('List:', list.toString());\nconsole.log('Size:', list.size);\nlist.reverse();\nconsole.log('Reversed:', list.toString());\nconsole.log('Pop:', list.pop());\nconsole.log('After pop:', list.toString());\n` },
  { id: 'ds-tree', name: 'Binary Search Tree', description: 'BST with insert, search, traversals', language: 'javascript', category: 'data-structures', tags: ['tree', 'bst', 'data-structures'],
    code: `// Binary Search Tree\nclass TreeNode {\n  constructor(val) { this.val = val; this.left = null; this.right = null; }\n}\n\nclass BST {\n  constructor() { this.root = null; }\n  \n  insert(val) {\n    const node = new TreeNode(val);\n    if (!this.root) { this.root = node; return this; }\n    let cur = this.root;\n    while (true) {\n      if (val < cur.val) { if (!cur.left) { cur.left = node; break; } cur = cur.left; }\n      else { if (!cur.right) { cur.right = node; break; } cur = cur.right; }\n    }\n    return this;\n  }\n  \n  search(val) {\n    let cur = this.root;\n    while (cur) {\n      if (val === cur.val) return true;\n      cur = val < cur.val ? cur.left : cur.right;\n    }\n    return false;\n  }\n  \n  inorder(node = this.root, result = []) {\n    if (node) { this.inorder(node.left, result); result.push(node.val); this.inorder(node.right, result); }\n    return result;\n  }\n  \n  preorder(node = this.root, result = []) {\n    if (node) { result.push(node.val); this.preorder(node.left, result); this.preorder(node.right, result); }\n    return result;\n  }\n  \n  height(node = this.root) {\n    if (!node) return 0;\n    return 1 + Math.max(this.height(node.left), this.height(node.right));\n  }\n}\n\nconst tree = new BST();\n[8, 3, 10, 1, 6, 14, 4, 7, 13].forEach(v => tree.insert(v));\nconsole.log('In-order:', tree.inorder());\nconsole.log('Pre-order:', tree.preorder());\nconsole.log('Height:', tree.height());\nconsole.log('Search 6:', tree.search(6));\nconsole.log('Search 99:', tree.search(99));\n` },
  { id: 'ds-hashmap', name: 'Hash Map', description: 'Hash map from scratch with collision handling', language: 'java', category: 'data-structures', tags: ['hashmap', 'data-structures'],
    code: `import java.util.*;\n\npublic class Main {\n    static class HashMap<K, V> {\n        private static class Entry<K, V> {\n            K key; V value; Entry<K, V> next;\n            Entry(K k, V v) { key = k; value = v; }\n        }\n        \n        private Entry<K, V>[] buckets;\n        private int size;\n        \n        @SuppressWarnings("unchecked")\n        HashMap(int capacity) { buckets = new Entry[capacity]; }\n        HashMap() { this(16); }\n        \n        private int index(K key) { return Math.abs(key.hashCode()) % buckets.length; }\n        \n        void put(K key, V value) {\n            int idx = index(key);\n            Entry<K, V> cur = buckets[idx];\n            while (cur != null) {\n                if (cur.key.equals(key)) { cur.value = value; return; }\n                cur = cur.next;\n            }\n            Entry<K, V> entry = new Entry<>(key, value);\n            entry.next = buckets[idx];\n            buckets[idx] = entry;\n            size++;\n        }\n        \n        V get(K key) {\n            Entry<K, V> cur = buckets[index(key)];\n            while (cur != null) {\n                if (cur.key.equals(key)) return cur.value;\n                cur = cur.next;\n            }\n            return null;\n        }\n        \n        int size() { return size; }\n    }\n    \n    public static void main(String[] args) {\n        HashMap<String, Integer> map = new HashMap<>();\n        map.put("apple", 5);\n        map.put("banana", 3);\n        map.put("cherry", 8);\n        map.put("apple", 10); // update\n        \n        System.out.println("apple: " + map.get("apple"));\n        System.out.println("banana: " + map.get("banana"));\n        System.out.println("cherry: " + map.get("cherry"));\n        System.out.println("size: " + map.size());\n    }\n}\n` },

  // Web
  { id: 'web-http', name: 'HTTP Server', description: 'Simple HTTP server in Go', language: 'go', category: 'web', tags: ['web', 'http', 'server'],
    code: `package main\n\nimport "fmt"\n\n// Note: This demonstrates Go HTTP concepts\n// In a real environment, you'd use net/http\n\ntype Request struct {\n\tMethod string\n\tPath   string\n\tBody   string\n}\n\ntype Response struct {\n\tStatus int\n\tBody   string\n}\n\ntype Handler func(Request) Response\n\ntype Router struct {\n\troutes map[string]Handler\n}\n\nfunc NewRouter() *Router {\n\treturn &Router{routes: make(map[string]Handler)}\n}\n\nfunc (r *Router) Handle(path string, h Handler) {\n\tr.routes[path] = h\n}\n\nfunc (r *Router) Dispatch(req Request) Response {\n\tif handler, ok := r.routes[req.Path]; ok {\n\t\treturn handler(req)\n\t}\n\treturn Response{Status: 404, Body: "Not Found"}\n}\n\nfunc main() {\n\trouter := NewRouter()\n\n\trouter.Handle("/", func(req Request) Response {\n\t\treturn Response{Status: 200, Body: "Hello, World!"}\n\t})\n\n\trouter.Handle("/api/users", func(req Request) Response {\n\t\treturn Response{Status: 200, Body: \`[{"id":1,"name":"Alice"},{"id":2,"name":"Bob"}]\`}\n\t})\n\n\t// Simulate requests\n\treqs := []Request{\n\t\t{Method: "GET", Path: "/"},\n\t\t{Method: "GET", Path: "/api/users"},\n\t\t{Method: "GET", Path: "/missing"},\n\t}\n\n\tfor _, req := range reqs {\n\t\tres := router.Dispatch(req)\n\t\tfmt.Printf("%s %s -> %d: %s\\n", req.Method, req.Path, res.Status, res.Body)\n\t}\n}\n` },
  { id: 'web-rest', name: 'REST API Pattern', description: 'REST API design pattern in TypeScript', language: 'typescript', category: 'web', tags: ['rest', 'api', 'typescript'],
    code: `// REST API Pattern - TypeScript\ninterface User {\n  id: number;\n  name: string;\n  email: string;\n  role: 'admin' | 'user';\n}\n\ninterface ApiResponse<T> {\n  success: boolean;\n  data?: T;\n  error?: string;\n  meta?: { total: number; page: number; };\n}\n\nclass UserService {\n  private users: User[] = [\n    { id: 1, name: 'Alice', email: 'alice@example.com', role: 'admin' },\n    { id: 2, name: 'Bob', email: 'bob@example.com', role: 'user' },\n    { id: 3, name: 'Charlie', email: 'charlie@example.com', role: 'user' },\n  ];\n\n  getAll(page = 1, limit = 10): ApiResponse<User[]> {\n    const start = (page - 1) * limit;\n    const data = this.users.slice(start, start + limit);\n    return { success: true, data, meta: { total: this.users.length, page } };\n  }\n\n  getById(id: number): ApiResponse<User> {\n    const user = this.users.find(u => u.id === id);\n    if (!user) return { success: false, error: 'User not found' };\n    return { success: true, data: user };\n  }\n\n  create(data: Omit<User, 'id'>): ApiResponse<User> {\n    const user = { ...data, id: this.users.length + 1 };\n    this.users.push(user);\n    return { success: true, data: user };\n  }\n\n  update(id: number, data: Partial<User>): ApiResponse<User> {\n    const idx = this.users.findIndex(u => u.id === id);\n    if (idx === -1) return { success: false, error: 'User not found' };\n    this.users[idx] = { ...this.users[idx], ...data };\n    return { success: true, data: this.users[idx] };\n  }\n\n  delete(id: number): ApiResponse<{ deleted: boolean }> {\n    const idx = this.users.findIndex(u => u.id === id);\n    if (idx === -1) return { success: false, error: 'User not found' };\n    this.users.splice(idx, 1);\n    return { success: true, data: { deleted: true } };\n  }\n}\n\n// Test\nconst service = new UserService();\nconsole.log('All users:', JSON.stringify(service.getAll(), null, 2));\nconsole.log('User 1:', JSON.stringify(service.getById(1), null, 2));\nconsole.log('Create:', JSON.stringify(service.create({ name: 'Dave', email: 'dave@test.com', role: 'user' }), null, 2));\nconsole.log('Update:', JSON.stringify(service.update(1, { name: 'Alice Updated' }), null, 2));\nconsole.log('Delete:', JSON.stringify(service.delete(3), null, 2));\nconsole.log('Final:', JSON.stringify(service.getAll(), null, 2));\n` },

  // Games  
  { id: 'game-tictactoe', name: 'Tic Tac Toe', description: 'Console-based tic tac toe game', language: 'python', category: 'games', tags: ['game', 'tictactoe'],
    code: `# Tic Tac Toe - AI vs Display\nclass TicTacToe:\n    def __init__(self):\n        self.board = [' '] * 9\n        self.current = 'X'\n    \n    def display(self):\n        for i in range(3):\n            row = ' | '.join(self.board[i*3:(i+1)*3])\n            print(f" {row}")\n            if i < 2: print("-----------")\n        print()\n    \n    def move(self, pos):\n        if self.board[pos] != ' ': return False\n        self.board[pos] = self.current\n        self.current = 'O' if self.current == 'X' else 'X'\n        return True\n    \n    def winner(self):\n        lines = [(0,1,2),(3,4,5),(6,7,8),(0,3,6),(1,4,7),(2,5,8),(0,4,8),(2,4,6)]\n        for a, b, c in lines:\n            if self.board[a] == self.board[b] == self.board[c] != ' ':\n                return self.board[a]\n        if ' ' not in self.board: return 'Draw'\n        return None\n    \n    def minimax(self, is_max):\n        w = self.winner()\n        if w == 'O': return 1\n        if w == 'X': return -1\n        if w == 'Draw': return 0\n        \n        best = -2 if is_max else 2\n        for i in range(9):\n            if self.board[i] == ' ':\n                self.board[i] = 'O' if is_max else 'X'\n                score = self.minimax(not is_max)\n                self.board[i] = ' '\n                best = max(best, score) if is_max else min(best, score)\n        return best\n    \n    def ai_move(self):\n        best_score, best_pos = -2, 0\n        for i in range(9):\n            if self.board[i] == ' ':\n                self.board[i] = 'O'\n                score = self.minimax(False)\n                self.board[i] = ' '\n                if score > best_score:\n                    best_score, best_pos = score, i\n        self.move(best_pos)\n        return best_pos\n\n# Demo game\ngame = TicTacToe()\nmoves = [0, 4, 2, 6]  # X moves\nfor i, m in enumerate(moves):\n    game.move(m)\n    print(f"X plays position {m}:")\n    game.display()\n    if game.winner(): break\n    pos = game.ai_move()\n    print(f"O (AI) plays position {pos}:")\n    game.display()\n    if game.winner(): break\n\nresult = game.winner()\nif result: print(f"Result: {'Draw' if result == 'Draw' else result + ' wins!'}")\nelse: print("Game in progress...")\n` },

  // Starter Projects
  { id: 'starter-js', name: 'JavaScript Starter', description: 'Modern JS with async/await, classes, modules pattern', language: 'javascript', category: 'starter', tags: ['starter', 'javascript'],
    code: `// JavaScript Starter Project\n// Modern patterns: async/await, destructuring, classes\n\nclass DataStore {\n  #data = new Map();\n  \n  set(key, value) { this.#data.set(key, { value, updatedAt: new Date() }); return this; }\n  get(key) { return this.#data.get(key)?.value ?? null; }\n  has(key) { return this.#data.has(key); }\n  delete(key) { return this.#data.delete(key); }\n  get size() { return this.#data.size; }\n  entries() { return [...this.#data.entries()].map(([k, v]) => ({ key: k, ...v })); }\n}\n\n// Async simulation\nconst delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));\n\nasync function fetchUser(id) {\n  await delay(10);\n  const users = { 1: 'Alice', 2: 'Bob', 3: 'Charlie' };\n  if (!users[id]) throw new Error(\`User \${id} not found\`);\n  return { id, name: users[id], active: true };\n}\n\nasync function main() {\n  // DataStore demo\n  const store = new DataStore();\n  store.set('config', { theme: 'dark', lang: 'en' });\n  store.set('version', '1.0.0');\n  console.log('Store size:', store.size);\n  console.log('Config:', store.get('config'));\n  \n  // Async demo\n  try {\n    const [user1, user2] = await Promise.all([fetchUser(1), fetchUser(2)]);\n    console.log('Users:', user1, user2);\n    \n    const user3 = await fetchUser(3);\n    console.log('User 3:', user3);\n  } catch (err) {\n    console.error('Error:', err.message);\n  }\n  \n  // Destructuring & spread\n  const { name, ...rest } = await fetchUser(1);\n  console.log(\`Hello, \${name}!\`, rest);\n}\n\nmain();\n` },
  { id: 'starter-py', name: 'Python Starter', description: 'Python with classes, decorators, generators', language: 'python', category: 'starter', tags: ['starter', 'python'],
    code: `# Python Starter Project\n# Patterns: decorators, generators, context managers, dataclasses\n\nfrom dataclasses import dataclass, field\nfrom typing import List, Optional\nimport time\n\n# Decorator\ndef timer(func):\n    def wrapper(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        elapsed = (time.time() - start) * 1000\n        print(f"  {func.__name__} took {elapsed:.2f}ms")\n        return result\n    return wrapper\n\n@dataclass\nclass Task:\n    title: str\n    done: bool = False\n    priority: int = 0\n    tags: List[str] = field(default_factory=list)\n\n@dataclass\nclass TaskManager:\n    tasks: List[Task] = field(default_factory=list)\n    \n    def add(self, title, priority=0, tags=None):\n        self.tasks.append(Task(title=title, priority=priority, tags=tags or []))\n        return self\n    \n    def complete(self, title):\n        for t in self.tasks:\n            if t.title == title: t.done = True\n        return self\n    \n    def pending(self):\n        return [t for t in self.tasks if not t.done]\n    \n    def by_priority(self):\n        return sorted(self.tasks, key=lambda t: -t.priority)\n\n# Generator\ndef fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b\n\n@timer\ndef main():\n    # Task manager\n    tm = TaskManager()\n    tm.add("Design API", priority=3, tags=["backend"])\n    tm.add("Write tests", priority=2, tags=["testing"])\n    tm.add("Deploy app", priority=1, tags=["devops"])\n    tm.add("Fix bug #42", priority=5, tags=["urgent"])\n    tm.complete("Design API")\n    \n    print("All tasks:")\n    for t in tm.by_priority():\n        status = "done" if t.done else "pending"\n        print(f"  [{status}] {t.title} (priority: {t.priority}, tags: {t.tags})")\n    \n    print(f"\\nPending: {len(tm.pending())} tasks")\n    \n    # Generator\n    fibs = list(fibonacci(10))\n    print(f"\\nFibonacci(10): {fibs}")\n\nmain()\n` },
  { id: 'starter-rust', name: 'Rust Starter', description: 'Rust ownership, structs, traits, error handling', language: 'rust', category: 'starter', tags: ['starter', 'rust'],
    code: `// Rust Starter Project\n// Patterns: structs, traits, enums, error handling\n\nuse std::fmt;\n\n#[derive(Debug)]\nstruct Task {\n    title: String,\n    done: bool,\n    priority: u8,\n}\n\nimpl Task {\n    fn new(title: &str, priority: u8) -> Self {\n        Task { title: title.to_string(), done: false, priority }\n    }\n    \n    fn complete(&mut self) { self.done = true; }\n}\n\nimpl fmt::Display for Task {\n    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {\n        let status = if self.done { "done" } else { "pending" };\n        write!(f, "[{}] {} (p:{})", status, self.title, self.priority)\n    }\n}\n\ntrait Summary {\n    fn summary(&self) -> String;\n}\n\nstruct TaskList {\n    tasks: Vec<Task>,\n}\n\nimpl TaskList {\n    fn new() -> Self { TaskList { tasks: Vec::new() } }\n    fn add(&mut self, title: &str, priority: u8) { self.tasks.push(Task::new(title, priority)); }\n    fn complete(&mut self, title: &str) {\n        if let Some(t) = self.tasks.iter_mut().find(|t| t.title == title) { t.complete(); }\n    }\n    fn pending(&self) -> Vec<&Task> { self.tasks.iter().filter(|t| !t.done).collect() }\n}\n\nimpl Summary for TaskList {\n    fn summary(&self) -> String {\n        let done = self.tasks.iter().filter(|t| t.done).count();\n        format!("{} total, {} done, {} pending", self.tasks.len(), done, self.pending().len())\n    }\n}\n\nfn fibonacci(n: u32) -> Vec<u64> {\n    let mut fibs = vec![0, 1];\n    for i in 2..n as usize { fibs.push(fibs[i-1] + fibs[i-2]); }\n    fibs[..n as usize].to_vec()\n}\n\nfn main() {\n    let mut list = TaskList::new();\n    list.add("Design API", 3);\n    list.add("Write tests", 2);\n    list.add("Deploy", 1);\n    list.add("Fix bug", 5);\n    list.complete("Design API");\n    \n    println!("Tasks:");\n    for task in &list.tasks { println!("  {}", task); }\n    println!("\\n{}", list.summary());\n    println!("\\nFibonacci(10): {:?}", fibonacci(10));\n}\n` },
  { id: 'starter-go', name: 'Go Starter', description: 'Go with structs, interfaces, goroutine patterns', language: 'go', category: 'starter', tags: ['starter', 'go'],
    code: `package main\n\nimport (\n\t"fmt"\n\t"sort"\n\t"strings"\n)\n\ntype Task struct {\n\tTitle    string\n\tDone     bool\n\tPriority int\n}\n\ntype TaskManager struct {\n\ttasks []Task\n}\n\nfunc NewTaskManager() *TaskManager { return &TaskManager{} }\n\nfunc (tm *TaskManager) Add(title string, priority int) {\n\ttm.tasks = append(tm.tasks, Task{Title: title, Priority: priority})\n}\n\nfunc (tm *TaskManager) Complete(title string) {\n\tfor i := range tm.tasks {\n\t\tif tm.tasks[i].Title == title { tm.tasks[i].Done = true }\n\t}\n}\n\nfunc (tm *TaskManager) Pending() []Task {\n\tvar result []Task\n\tfor _, t := range tm.tasks {\n\t\tif !t.Done { result = append(result, t) }\n\t}\n\treturn result\n}\n\nfunc (tm *TaskManager) ByPriority() []Task {\n\tsorted := make([]Task, len(tm.tasks))\n\tcopy(sorted, tm.tasks)\n\tsort.Slice(sorted, func(i, j int) bool { return sorted[i].Priority > sorted[j].Priority })\n\treturn sorted\n}\n\n// Stringer interface\nfunc (t Task) String() string {\n\tstatus := "pending"\n\tif t.Done { status = "done" }\n\treturn fmt.Sprintf("[%s] %s (p:%d)", status, t.Title, t.Priority)\n}\n\nfunc fibonacci(n int) []int {\n\tfibs := []int{0, 1}\n\tfor i := 2; i < n; i++ { fibs = append(fibs, fibs[i-1]+fibs[i-2]) }\n\treturn fibs[:n]\n}\n\nfunc main() {\n\ttm := NewTaskManager()\n\ttm.Add("Design API", 3)\n\ttm.Add("Write tests", 2)\n\ttm.Add("Deploy app", 1)\n\ttm.Add("Fix bug #42", 5)\n\ttm.Complete("Design API")\n\n\tfmt.Println("All tasks (by priority):")\n\tfor _, t := range tm.ByPriority() { fmt.Printf("  %s\\n", t) }\n\tfmt.Printf("\\nPending: %d tasks\\n", len(tm.Pending()))\n\t\n\tfibs := fibonacci(10)\n\tstrs := make([]string, len(fibs))\n\tfor i, f := range fibs { strs[i] = fmt.Sprintf("%d", f) }\n\tfmt.Printf("Fibonacci(10): [%s]\\n", strings.Join(strs, ", "))\n}\n` },
  { id: 'starter-cpp', name: 'C++ Starter', description: 'Modern C++17 with templates, smart pointers', language: 'cpp', category: 'starter', tags: ['starter', 'cpp'],
    code: `// C++17 Starter Project\n#include <iostream>\n#include <vector>\n#include <algorithm>\n#include <memory>\n#include <string>\n#include <numeric>\n\nstruct Task {\n    std::string title;\n    bool done = false;\n    int priority = 0;\n    \n    Task(std::string t, int p) : title(std::move(t)), priority(p) {}\n    void complete() { done = true; }\n    \n    friend std::ostream& operator<<(std::ostream& os, const Task& t) {\n        os << "[" << (t.done ? "done" : "pending") << "] " << t.title << " (p:" << t.priority << ")";\n        return os;\n    }\n};\n\nclass TaskManager {\n    std::vector<std::unique_ptr<Task>> tasks;\npublic:\n    void add(const std::string& title, int priority) {\n        tasks.push_back(std::make_unique<Task>(title, priority));\n    }\n    \n    void complete(const std::string& title) {\n        auto it = std::find_if(tasks.begin(), tasks.end(),\n            [&](const auto& t) { return t->title == title; });\n        if (it != tasks.end()) (*it)->complete();\n    }\n    \n    int pendingCount() const {\n        return std::count_if(tasks.begin(), tasks.end(),\n            [](const auto& t) { return !t->done; });\n    }\n    \n    void printSorted() const {\n        std::vector<Task*> sorted;\n        for (const auto& t : tasks) sorted.push_back(t.get());\n        std::sort(sorted.begin(), sorted.end(),\n            [](Task* a, Task* b) { return a->priority > b->priority; });\n        for (const auto* t : sorted) std::cout << "  " << *t << "\\n";\n    }\n};\n\nstd::vector<long long> fibonacci(int n) {\n    std::vector<long long> fibs(n);\n    fibs[0] = 0; fibs[1] = 1;\n    for (int i = 2; i < n; i++) fibs[i] = fibs[i-1] + fibs[i-2];\n    return fibs;\n}\n\nint main() {\n    TaskManager tm;\n    tm.add("Design API", 3);\n    tm.add("Write tests", 2);\n    tm.add("Deploy", 1);\n    tm.add("Fix bug", 5);\n    tm.complete("Design API");\n    \n    std::cout << "Tasks (by priority):\\n";\n    tm.printSorted();\n    std::cout << "\\nPending: " << tm.pendingCount() << " tasks\\n";\n    \n    auto fibs = fibonacci(10);\n    std::cout << "\\nFibonacci(10): ";\n    for (size_t i = 0; i < fibs.size(); i++)\n        std::cout << fibs[i] << (i < fibs.size()-1 ? ", " : "");\n    std::cout << "\\n";\n    return 0;\n}\n` },
  { id: 'starter-ruby', name: 'Ruby Starter', description: 'Ruby with classes, blocks, enumerable', language: 'ruby', category: 'starter', tags: ['starter', 'ruby'],
    code: `# Ruby Starter Project\n# Patterns: classes, modules, blocks, enumerable\n\nmodule Prioritizable\n  def high_priority?\n    priority >= 4\n  end\nend\n\nclass Task\n  include Prioritizable\n  attr_accessor :title, :done, :priority, :tags\n\n  def initialize(title, priority: 0, tags: [])\n    @title = title\n    @done = false\n    @priority = priority\n    @tags = tags\n  end\n\n  def complete!\n    @done = true\n    self\n  end\n\n  def to_s\n    status = @done ? "done" : "pending"\n    "[#{status}] #{@title} (p:#{@priority})"\n  end\nend\n\nclass TaskManager\n  include Enumerable\n\n  def initialize\n    @tasks = []\n  end\n\n  def add(title, priority: 0, tags: [])\n    @tasks << Task.new(title, priority: priority, tags: tags)\n    self\n  end\n\n  def complete(title)\n    @tasks.find { |t| t.title == title }&.complete!\n    self\n  end\n\n  def each(&block)\n    @tasks.each(&block)\n  end\n\n  def pending\n    reject(&:done)\n  end\n\n  def by_priority\n    sort_by { |t| -t.priority }\n  end\n\n  def summary\n    done = count(&:done)\n    "#{count} total, #{done} done, #{pending.count} pending"\n  end\nend\n\ndef fibonacci(n)\n  (2...n).reduce([0, 1]) { |fibs, _| fibs << fibs[-1] + fibs[-2] }\nend\n\n# Demo\ntm = TaskManager.new\ntm.add("Design API", priority: 3, tags: ["backend"])\n  .add("Write tests", priority: 2, tags: ["testing"])\n  .add("Deploy app", priority: 1, tags: ["devops"])\n  .add("Fix bug #42", priority: 5, tags: ["urgent"])\n  .complete("Design API")\n\nputs "Tasks (by priority):"\ntm.by_priority.each { |t| puts "  #{t}" }\nputs "\\n#{tm.summary}"\nputs "High priority: #{tm.select(&:high_priority?).map(&:title).join(', ')}"\nputs "\\nFibonacci(10): #{fibonacci(10).inspect}"\n` },

  // Utilities
  { id: 'util-json', name: 'JSON Parser', description: 'Simple JSON parser from scratch', language: 'javascript', category: 'utilities', tags: ['json', 'parser', 'utilities'],
    code: `// Mini JSON Parser from scratch\nclass JSONParser {\n  constructor(input) { this.input = input; this.pos = 0; }\n  \n  parse() {\n    this.skipWhitespace();\n    const result = this.parseValue();\n    this.skipWhitespace();\n    if (this.pos < this.input.length) throw new Error(\`Unexpected char at \${this.pos}\`);\n    return result;\n  }\n  \n  parseValue() {\n    this.skipWhitespace();\n    const ch = this.input[this.pos];\n    if (ch === '"') return this.parseString();\n    if (ch === '{') return this.parseObject();\n    if (ch === '[') return this.parseArray();\n    if (ch === 't' || ch === 'f') return this.parseBool();\n    if (ch === 'n') return this.parseNull();\n    if (ch === '-' || (ch >= '0' && ch <= '9')) return this.parseNumber();\n    throw new Error(\`Unexpected char '\${ch}' at pos \${this.pos}\`);\n  }\n  \n  parseString() {\n    this.pos++; // skip opening "\n    let str = '';\n    while (this.pos < this.input.length && this.input[this.pos] !== '"') {\n      if (this.input[this.pos] === '\\\\') { this.pos++; str += this.input[this.pos]; }\n      else str += this.input[this.pos];\n      this.pos++;\n    }\n    this.pos++; // skip closing "\n    return str;\n  }\n  \n  parseNumber() {\n    let start = this.pos;\n    if (this.input[this.pos] === '-') this.pos++;\n    while (this.pos < this.input.length && /[0-9.eE+-]/.test(this.input[this.pos])) this.pos++;\n    return Number(this.input.slice(start, this.pos));\n  }\n  \n  parseObject() {\n    this.pos++; // skip {\n    const obj = {};\n    this.skipWhitespace();\n    if (this.input[this.pos] === '}') { this.pos++; return obj; }\n    while (true) {\n      this.skipWhitespace();\n      const key = this.parseString();\n      this.skipWhitespace();\n      this.pos++; // skip :\n      obj[key] = this.parseValue();\n      this.skipWhitespace();\n      if (this.input[this.pos] === '}') { this.pos++; break; }\n      this.pos++; // skip ,\n    }\n    return obj;\n  }\n  \n  parseArray() {\n    this.pos++; // skip [\n    const arr = [];\n    this.skipWhitespace();\n    if (this.input[this.pos] === ']') { this.pos++; return arr; }\n    while (true) {\n      arr.push(this.parseValue());\n      this.skipWhitespace();\n      if (this.input[this.pos] === ']') { this.pos++; break; }\n      this.pos++; // skip ,\n    }\n    return arr;\n  }\n  \n  parseBool() {\n    if (this.input.startsWith('true', this.pos)) { this.pos += 4; return true; }\n    this.pos += 5; return false;\n  }\n  \n  parseNull() { this.pos += 4; return null; }\n  \n  skipWhitespace() { while (this.pos < this.input.length && ' \\t\\n\\r'.includes(this.input[this.pos])) this.pos++; }\n}\n\n// Test\nconst json = '{"name": "Alice", "age": 30, "hobbies": ["coding", "reading"], "active": true, "address": null}';\nconst parsed = new JSONParser(json).parse();\nconsole.log('Parsed:', JSON.stringify(parsed, null, 2));\nconsole.log('Name:', parsed.name);\nconsole.log('Hobbies:', parsed.hobbies);\n` },
  { id: 'util-cli', name: 'CLI Framework', description: 'Command-line argument parser', language: 'python', category: 'utilities', tags: ['cli', 'argparse', 'utilities'],
    code: `# Mini CLI Framework\nclass CLI:\n    def __init__(self, name, description=""):\n        self.name = name\n        self.description = description\n        self.commands = {}\n    \n    def command(self, name, help=""):\n        def decorator(func):\n            self.commands[name] = {"func": func, "help": help}\n            return func\n        return decorator\n    \n    def run(self, args):\n        if not args or args[0] in ("--help", "-h"):\n            self.show_help()\n            return\n        cmd = args[0]\n        if cmd not in self.commands:\n            print(f"Unknown command: {cmd}")\n            self.show_help()\n            return\n        self.commands[cmd]["func"](args[1:])\n    \n    def show_help(self):\n        print(f"\\n{self.name}")\n        if self.description: print(f"  {self.description}\\n")\n        print("Commands:")\n        for name, info in self.commands.items():\n            print(f"  {name:15s} {info['help']}")\n        print()\n\n# Build a demo CLI\napp = CLI("taskctl", "Task management CLI")\n\ntasks = []\n\n@app.command("add", help="Add a new task")\ndef add_task(args):\n    if not args: print("Usage: add <task>"); return\n    tasks.append({"title": " ".join(args), "done": False})\n    print(f"Added: {tasks[-1]['title']}")\n\n@app.command("list", help="List all tasks")\ndef list_tasks(args):\n    if not tasks: print("No tasks yet"); return\n    for i, t in enumerate(tasks, 1):\n        status = "x" if t["done"] else " "\n        print(f"  {i}. [{status}] {t['title']}")\n\n@app.command("done", help="Mark task as done")\ndef done_task(args):\n    if not args: print("Usage: done <number>"); return\n    idx = int(args[0]) - 1\n    if 0 <= idx < len(tasks):\n        tasks[idx]["done"] = True\n        print(f"Completed: {tasks[idx]['title']}")\n\n@app.command("stats", help="Show statistics")\ndef show_stats(args):\n    total = len(tasks)\n    done = sum(1 for t in tasks if t["done"])\n    print(f"Total: {total}, Done: {done}, Pending: {total - done}")\n\n# Simulate CLI usage\nprint("=== Task CLI Demo ===")\nfor cmd in [\n    ["add", "Design", "the", "API"],\n    ["add", "Write", "unit", "tests"],\n    ["add", "Deploy", "to", "production"],\n    ["list"],\n    ["done", "1"],\n    ["list"],\n    ["stats"],\n]:\n    print(f"\\n$ taskctl {' '.join(cmd)}")\n    app.run(cmd)\n` },

  // ML / Data
  { id: 'ml-stats', name: 'Statistics Library', description: 'Basic statistics functions from scratch', language: 'python', category: 'ml', tags: ['statistics', 'math', 'ml'],
    code: `# Statistics Library from Scratch\nimport math\n\ndef mean(data): return sum(data) / len(data)\n\ndef median(data):\n    s = sorted(data)\n    n = len(s)\n    if n % 2 == 0: return (s[n//2 - 1] + s[n//2]) / 2\n    return s[n // 2]\n\ndef mode(data):\n    freq = {}\n    for x in data: freq[x] = freq.get(x, 0) + 1\n    max_count = max(freq.values())\n    return [k for k, v in freq.items() if v == max_count]\n\ndef variance(data, sample=True):\n    m = mean(data)\n    n = len(data) - (1 if sample else 0)\n    return sum((x - m) ** 2 for x in data) / n\n\ndef std_dev(data, sample=True): return math.sqrt(variance(data, sample))\n\ndef percentile(data, p):\n    s = sorted(data)\n    k = (len(s) - 1) * (p / 100)\n    f = math.floor(k)\n    c = math.ceil(k)\n    if f == c: return s[int(k)]\n    return s[f] * (c - k) + s[c] * (k - f)\n\ndef correlation(x, y):\n    n = len(x)\n    mx, my = mean(x), mean(y)\n    num = sum((x[i] - mx) * (y[i] - my) for i in range(n))\n    dx = math.sqrt(sum((xi - mx) ** 2 for xi in x))\n    dy = math.sqrt(sum((yi - my) ** 2 for yi in y))\n    return num / (dx * dy) if dx * dy != 0 else 0\n\ndef linear_regression(x, y):\n    n = len(x)\n    mx, my = mean(x), mean(y)\n    num = sum((x[i] - mx) * (y[i] - my) for i in range(n))\n    den = sum((xi - mx) ** 2 for xi in x)\n    slope = num / den if den != 0 else 0\n    intercept = my - slope * mx\n    return slope, intercept\n\n# Demo\ndata = [23, 45, 12, 67, 34, 89, 56, 78, 41, 63, 29, 51, 74, 38, 82]\nprint(f"Data: {data}")\nprint(f"Mean: {mean(data):.2f}")\nprint(f"Median: {median(data):.2f}")\nprint(f"Mode: {mode(data)}")\nprint(f"Std Dev: {std_dev(data):.2f}")\nprint(f"P25: {percentile(data, 25):.2f}")\nprint(f"P75: {percentile(data, 75):.2f}")\n\nx = [1, 2, 3, 4, 5, 6, 7, 8]\ny = [2.1, 4.0, 5.8, 8.1, 9.9, 12.1, 13.8, 16.2]\nslope, intercept = linear_regression(x, y)\nprint(f"\\nLinear Regression: y = {slope:.2f}x + {intercept:.2f}")\nprint(f"Correlation: {correlation(x, y):.4f}")\n` },

  // API
  { id: 'api-fetch', name: 'API Client', description: 'HTTP client with retry and error handling', language: 'javascript', category: 'api', tags: ['api', 'http', 'fetch'],
    code: `// Robust API Client Pattern\nclass ApiClient {\n  constructor(baseUrl, options = {}) {\n    this.baseUrl = baseUrl;\n    this.timeout = options.timeout || 5000;\n    this.retries = options.retries || 3;\n    this.headers = { 'Content-Type': 'application/json', ...options.headers };\n  }\n\n  async request(method, path, { body, params, headers } = {}) {\n    const url = new URL(path, this.baseUrl);\n    if (params) Object.entries(params).forEach(([k, v]) => url.searchParams.set(k, v));\n\n    for (let attempt = 1; attempt <= this.retries; attempt++) {\n      try {\n        const config = {\n          method,\n          headers: { ...this.headers, ...headers },\n          body: body ? JSON.stringify(body) : undefined,\n        };\n        // Simulated response\n        console.log(\`[\${method}] \${url.pathname} (attempt \${attempt})\`);\n        return { ok: true, data: { method, path, body, attempt } };\n      } catch (err) {\n        if (attempt === this.retries) throw err;\n        const delay = Math.pow(2, attempt) * 100;\n        console.log(\`  Retry in \${delay}ms...\`);\n      }\n    }\n  }\n\n  get(path, opts) { return this.request('GET', path, opts); }\n  post(path, body, opts) { return this.request('POST', path, { ...opts, body }); }\n  put(path, body, opts) { return this.request('PUT', path, { ...opts, body }); }\n  delete(path, opts) { return this.request('DELETE', path, opts); }\n}\n\n// Usage\nconst api = new ApiClient('https://api.example.com', {\n  headers: { 'Authorization': 'Bearer token123' },\n  retries: 3,\n});\n\nasync function main() {\n  const users = await api.get('/users', { params: { page: '1', limit: '10' } });\n  console.log('Users:', users);\n\n  const newUser = await api.post('/users', { name: 'Alice', email: 'alice@test.com' });\n  console.log('Created:', newUser);\n\n  const updated = await api.put('/users/1', { name: 'Alice Updated' });\n  console.log('Updated:', updated);\n\n  const deleted = await api.delete('/users/1');\n  console.log('Deleted:', deleted);\n}\n\nmain().catch(console.error);\n` },
  { id: 'starter-c', name: 'C Starter', description: 'C with structs, pointers, dynamic memory', language: 'c', category: 'starter', tags: ['starter', 'c'],
    code: `/* C Starter Project - Dynamic Array */\n#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\ntypedef struct {\n    int *data;\n    int size;\n    int capacity;\n} DynArray;\n\nDynArray* da_create(int cap) {\n    DynArray *arr = malloc(sizeof(DynArray));\n    arr->data = malloc(cap * sizeof(int));\n    arr->size = 0;\n    arr->capacity = cap;\n    return arr;\n}\n\nvoid da_push(DynArray *arr, int val) {\n    if (arr->size >= arr->capacity) {\n        arr->capacity *= 2;\n        arr->data = realloc(arr->data, arr->capacity * sizeof(int));\n    }\n    arr->data[arr->size++] = val;\n}\n\nint da_pop(DynArray *arr) {\n    if (arr->size == 0) return -1;\n    return arr->data[--arr->size];\n}\n\nvoid da_print(DynArray *arr) {\n    printf("[");\n    for (int i = 0; i < arr->size; i++)\n        printf("%d%s", arr->data[i], i < arr->size - 1 ? ", " : "");\n    printf("] (size: %d, cap: %d)\\n", arr->size, arr->capacity);\n}\n\nvoid da_sort(DynArray *arr) {\n    for (int i = 0; i < arr->size - 1; i++)\n        for (int j = 0; j < arr->size - i - 1; j++)\n            if (arr->data[j] > arr->data[j+1]) {\n                int tmp = arr->data[j];\n                arr->data[j] = arr->data[j+1];\n                arr->data[j+1] = tmp;\n            }\n}\n\nvoid da_free(DynArray *arr) { free(arr->data); free(arr); }\n\nint main() {\n    DynArray *arr = da_create(4);\n    int values[] = {42, 17, 83, 5, 61, 29, 94, 38};\n    \n    for (int i = 0; i < 8; i++) da_push(arr, values[i]);\n    \n    printf("Array: "); da_print(arr);\n    da_sort(arr);\n    printf("Sorted: "); da_print(arr);\n    printf("Popped: %d\\n", da_pop(arr));\n    printf("After pop: "); da_print(arr);\n    \n    da_free(arr);\n    return 0;\n}\n` },
  { id: 'starter-php', name: 'PHP Starter', description: 'PHP OOP with traits, interfaces', language: 'php', category: 'starter', tags: ['starter', 'php'],
    code: `<?php\n// PHP Starter Project - OOP Patterns\n\ninterface Printable {\n    public function toString(): string;\n}\n\ntrait Timestampable {\n    private \\DateTime $createdAt;\n    \n    public function setCreated(): void {\n        $this->createdAt = new \\DateTime();\n    }\n    \n    public function getCreated(): string {\n        return $this->createdAt->format('Y-m-d H:i:s');\n    }\n}\n\nclass Task implements Printable {\n    use Timestampable;\n    \n    public function __construct(\n        private string $title,\n        private int $priority = 0,\n        private bool $done = false\n    ) {\n        $this->setCreated();\n    }\n    \n    public function complete(): self {\n        $this->done = true;\n        return $this;\n    }\n    \n    public function isDone(): bool { return $this->done; }\n    public function getTitle(): string { return $this->title; }\n    public function getPriority(): int { return $this->priority; }\n    \n    public function toString(): string {\n        $status = $this->done ? 'done' : 'pending';\n        return \"[{$status}] {$this->title} (p:{$this->priority})\";\n    }\n}\n\nclass TaskManager {\n    private array $tasks = [];\n    \n    public function add(string $title, int $priority = 0): self {\n        $this->tasks[] = new Task($title, $priority);\n        return $this;\n    }\n    \n    public function complete(string $title): self {\n        foreach ($this->tasks as $task) {\n            if ($task->getTitle() === $title) $task->complete();\n        }\n        return $this;\n    }\n    \n    public function pending(): array {\n        return array_filter($this->tasks, fn(Task $t) => !$t->isDone());\n    }\n    \n    public function byPriority(): array {\n        $sorted = [...$this->tasks];\n        usort($sorted, fn(Task $a, Task $b) => $b->getPriority() - $a->getPriority());\n        return $sorted;\n    }\n}\n\n$tm = new TaskManager();\n$tm->add('Design API', 3)\n   ->add('Write tests', 2)\n   ->add('Deploy app', 1)\n   ->add('Fix bug #42', 5)\n   ->complete('Design API');\n\necho \"Tasks (by priority):\\n\";\nforeach ($tm->byPriority() as $task) {\n    echo \"  \" . $task->toString() . \"\\n\";\n}\necho \"\\nPending: \" . count($tm->pending()) . \" tasks\\n\";\n?>\n` },
];

// ─── Routes ─────────────────────────────────────────────────────────

// Save a workspace
router.post('/', authMiddleware, asyncHandler(async (req, res) => {
  const { name, description, code, language, files, tags, isPublic } = req.body;
  if (!name) return res.status(400).json({ error: true, message: 'Name is required' });
  if (!code && (!files || files.length === 0)) return res.status(400).json({ error: true, message: 'Code or files required' });
  if (code && code.length > MAX_SIZE) return res.status(400).json({ error: true, message: 'Code too large (max 500KB)' });

  const userId = req.user.userId;

  // MongoDB path
  if (getConnectionStatus() && Workspace) {
    const count = await Workspace.countDocuments({ userId });
    if (count >= MAX_WORKSPACES) return res.status(400).json({ error: true, message: `Max ${MAX_WORKSPACES} workspaces` });
    const ws = await Workspace.create({
      userId, name: name.trim(), description: (description || '').trim(),
      code: code || '', language: language || 'javascript',
      files: files || [], tags: tags || [], isPublic: !!isPublic,
    });
    return res.json({ success: true, workspace: ws.toObject() });
  }

  // In-memory fallback
  const userWs = memWorkspaces.get(userId) || [];
  if (userWs.length >= MAX_WORKSPACES) return res.status(400).json({ error: true, message: `Max ${MAX_WORKSPACES} workspaces` });
  const ws = {
    _id: Date.now().toString(36) + Math.random().toString(36).slice(2, 8),
    userId, name: name.trim(), description: (description || '').trim(),
    code: code || '', language: language || 'javascript',
    files: files || [], tags: tags || [], isPublic: !!isPublic,
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
    openCount: 0,
  };
  userWs.unshift(ws);
  memWorkspaces.set(userId, userWs);
  res.json({ success: true, workspace: ws });
}));

// List user's workspaces
router.get('/', authMiddleware, asyncHandler(async (req, res) => {
  const userId = req.user.userId;
  const page = parseInt(req.query.page) || 1;
  const limit = Math.min(parseInt(req.query.limit) || 20, 50);

  if (getConnectionStatus() && Workspace) {
    const result = await Workspace.getUserWorkspaces(userId, { page, limit });
    return res.json(result);
  }

  const userWs = memWorkspaces.get(userId) || [];
  const start = (page - 1) * limit;
  res.json({
    workspaces: userWs.slice(start, start + limit),
    total: userWs.length, page, pages: Math.ceil(userWs.length / limit),
  });
}));

// Get a specific workspace
router.get('/:id', authMiddleware, asyncHandler(async (req, res) => {
  const userId = req.user.userId;

  if (getConnectionStatus() && Workspace) {
    const ws = await Workspace.findById(req.params.id);
    if (!ws) return res.status(404).json({ error: true, message: 'Workspace not found' });
    if (ws.userId !== userId && !ws.isPublic) return res.status(403).json({ error: true, message: 'Access denied' });
    ws.openCount++;
    ws.lastOpenedAt = new Date();
    await ws.save();
    return res.json({ workspace: ws.toObject() });
  }

  const userWs = memWorkspaces.get(userId) || [];
  const ws = userWs.find(w => w._id === req.params.id);
  if (!ws) return res.status(404).json({ error: true, message: 'Workspace not found' });
  ws.openCount = (ws.openCount || 0) + 1;
  res.json({ workspace: ws });
}));

// Update a workspace
router.put('/:id', authMiddleware, asyncHandler(async (req, res) => {
  const userId = req.user.userId;
  const updates = req.body;

  if (getConnectionStatus() && Workspace) {
    const ws = await Workspace.findOne({ _id: req.params.id, userId });
    if (!ws) return res.status(404).json({ error: true, message: 'Workspace not found' });
    Object.assign(ws, updates);
    await ws.save();
    return res.json({ success: true, workspace: ws.toObject() });
  }

  const userWs = memWorkspaces.get(userId) || [];
  const idx = userWs.findIndex(w => w._id === req.params.id);
  if (idx === -1) return res.status(404).json({ error: true, message: 'Workspace not found' });
  Object.assign(userWs[idx], updates, { updatedAt: new Date().toISOString() });
  res.json({ success: true, workspace: userWs[idx] });
}));

// Delete a workspace
router.delete('/:id', authMiddleware, asyncHandler(async (req, res) => {
  const userId = req.user.userId;

  if (getConnectionStatus() && Workspace) {
    const result = await Workspace.deleteOne({ _id: req.params.id, userId });
    if (result.deletedCount === 0) return res.status(404).json({ error: true, message: 'Not found' });
    return res.json({ success: true });
  }

  const userWs = memWorkspaces.get(userId) || [];
  const idx = userWs.findIndex(w => w._id === req.params.id);
  if (idx === -1) return res.status(404).json({ error: true, message: 'Not found' });
  userWs.splice(idx, 1);
  res.json({ success: true });
}));

// Fork a workspace
router.post('/:id/fork', authMiddleware, asyncHandler(async (req, res) => {
  const userId = req.user.userId;

  if (getConnectionStatus() && Workspace) {
    const original = await Workspace.findById(req.params.id);
    if (!original) return res.status(404).json({ error: true, message: 'Not found' });
    if (!original.isPublic && original.userId !== userId) return res.status(403).json({ error: true, message: 'Access denied' });
    const forked = await Workspace.create({
      userId, name: `${original.name} (fork)`, description: original.description,
      code: original.code, language: original.language, files: original.files,
      tags: original.tags, forkedFrom: original._id,
    });
    original.forkCount++;
    await original.save();
    return res.json({ success: true, workspace: forked.toObject() });
  }

  res.json({ success: false, message: 'Fork requires database connection' });
}));

// ─── Templates ──────────────────────────────────────────────────────

router.get('/templates/all', asyncHandler(async (req, res) => {
  const { category } = req.query;
  let templates = TEMPLATES;
  if (category) templates = templates.filter(t => t.category === category);
  res.json({
    templates: templates.map(t => ({
      id: t.id, name: t.name, description: t.description,
      language: t.language, category: t.category, tags: t.tags,
    })),
    categories: ['algorithms', 'data-structures', 'web', 'api', 'games', 'ml', 'utilities', 'starter'],
  });
}));

router.get('/templates/:id', asyncHandler(async (req, res) => {
  const template = TEMPLATES.find(t => t.id === req.params.id);
  if (!template) return res.status(404).json({ error: true, message: 'Template not found' });
  res.json({ template });
}));

module.exports = router;
